### ISSUE TITLE
The application crashes when I try to open the application

### ISSUE THREAD

**Issue by friendsmobile** [igravitystudios/matchimals.fun#29]
# Project Information

* Repository: https://github.com/igravitystudios/matchimals.fun
* Project Name: matchimals.fun
* My Github Account: https://github.com/friendsmobile

# Expected behavior

When I try to open the application, then the application should be opened. So that the user can easily play the game
 
# Actual behavior

The application crashes when I try to open the application

# How to reproduce

* [Download ](https://play.google.com/store/apps/details?id=com.matchimals)the application
* After installing the application, try opening it
* Note the BUG

* Browser/App version:  Current Version 0.1.0
* Operating system: 6.0

# Recording Of The Bug

![20190529_032408](https://user-images.githubusercontent.com/51118734/58516419-bc70e380-815c-11e9-944e-d7c2ef24b675.gif)

# Logcat

<pre><code>E/AndroidRuntime( 7954): FATAL EXCEPTION: create_react_context

E/AndroidRuntime( 7954): Process: com.matchimals, PID: 7954

E/AndroidRuntime( 7954): java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libreactnativejni.so

E/AndroidRuntime( 7954): 	at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:738)

E/AndroidRuntime( 7954): 	at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:591)

E/AndroidRuntime( 7954): 	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:529)

E/AndroidRuntime( 7954): 	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:484)

E/AndroidRuntime( 7954): 	at com.facebook.react.bridge.ReactBridge.staticInit(ReactBridge.java:31)

E/AndroidRuntime( 7954): 	at com.facebook.react.bridge.NativeMap.<clinit>(NativeMap.java:19)

E/AndroidRuntime( 7954): 	at com.facebook.react.jscexecutor.JSCExecutorFactory.create(JSCExecutorFactory.java:25)

E/AndroidRuntime( 7954): 	at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:944)

E/AndroidRuntime( 7954): 	at java.lang.Thread.run(Thread.java:818)
</code></pre>

**Comment by chrisheninger** [comment]
Looks like it's something to do with 32-bit vs 64-bit dependencies– thanks for the detailed report and logs– extremely helpful. 🙂

Gonna try to replicate it on my end and I'll let you know if/when I push a fix. 👍

**Comment by chrisheninger** [comment]
Hey @friendsmobile– I was never able to replicate this issue locally– I don't have a Galaxy and I couldn't get the emulator to run with a different CPU than x86. 😓

Regardless... I *did* push an update to the Google Play Store with a recommendation from a relevant react-native github issue I found. (https://github.com/facebook/react-native/issues/2814)

Could you give it another try after uninstalling/reinstalling and let me know if it loads? Also– which phone are you using?

**Comment by friendsmobile** [comment]
I have tried more than once
I have Galaxy j7 2016

**Comment by friendsmobile** [comment]
Thank you I have uninstalled and reinstalled the application so the application is working fine now my mobile phone

**Comment by friendsmobile** [comment]
![20190609_142119](https://user-images.githubusercontent.com/51118734/59157330-baacf700-8a5d-11e9-9ea2-df21ba51a794.gif)

**Comment by chrisheninger** [comment]
This is very good to hear! Thank you for the detailed bug report– I'm glad that we were able to fix it. 😄 

Enjoy the game, and keep an eye out for updates in the coming weeks! I'm hopefully going to be

**Comment by friendsmobile** [comment]
welcome sir
